
CREATE DATABASE Test;
GO

USE Test;
GO

CREATE TABLE Users (
    Id VARCHAR(100) NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Created DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    Modified DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    LastLogin DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    Token VARCHAR(255) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE Phones (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES Users(Id),
    Number VARCHAR(15) NOT NULL,
    CityCode VARCHAR(5) NOT NULL,
    CountryCode VARCHAR(5) NOT NULL
);

GO